name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: nestjs-notes-ecr-repo
          registry: 857095442896.dkr.ecr.eu-central-1.amazonaws.com
          addLatest: true
        env:
          PORT: 80
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URI }}
      - name: Download ECS Task Definition
        id: task-definition
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
          TASK_FAMILY: nestjs-notes-cluster
          TASK_DEFINITION: ${{ secrets.TASK_DEFINITION }}
        run: |
            aws ecs register-task-definition --region "$AWS_DEFAULT_REGION" --cli-input-json "$NEW_TASK_DEFINITION"



