name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: nestjs-notes-ecr-repo
          registry: 857095442896.dkr.ecr.eu-central-1.amazonaws.com
          addLatest: true
        env:
          PORT: 80
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URI }}
      - name: Download ECS Task Definition
        id: task-definition
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
          AWS_REGION: 'eu-central-1'
          TASK_FAMILY: nestjs-notes-cluster
        run: |
            aws ecs describe-task-definition --task-definition "$TASK_FAMILY" --region "$AWS_DEFAULT_REGION" > task-definition.json
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: nestjs-notes-cluster-service
          cluster: nestjs-notes-cluster
          wait-for-service-stability: true



